apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 10.26.0.176:5000/lavagna-build:164
          env:
            - name: DB_DIALECT
              value: "PGSQL"
            - name: DB_URL
              value: "jdbc:postgresql://postgresql:5432/lavagna"
            - name: DB_USERNAME
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          ports:
            - containerPort: 8080
