apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-main-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      environment: main
