apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # Specify a nodePort if you want a specific port allocated, or leave it out for an automatic allocation
  selector:
    app: registry
