apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard